### ISSUE TITLE
It it possible to separate the Win 10/11 bridge from the RPC application?

### ISSUE THREAD

**Issue by Mudkip2345** [T0biasCZe/Windows-Media-Player-Discord-RPC#14]
I am running Windows 7 SP1. When you change the required .net version in the config file to 4.8, and then launch it, it appears to work normally until it tries to load the system media controls portion. I assume this is because it's looking for Win 10's media system and obviously can't find it, but when this happens instead of allowing the other portion to work normally it forces the whole program to close. I was wondering if it would be possible to separate these, for the purposes of NT 6.x compatibility?

**Comment by T0biasCZe** [comment]
v1.0.1 should work on Win7

**Comment by T0biasCZe** [comment]
I made version without the System Media Control functionality that should work on Windows 7
https://github.com/T0biasCZe/Windows-Media-Player-Discord-RPC/releases/tag/v2.2.3
And as a replacement for the system media control i implemented media keys input into the app itself (not tested though, dont have keyboard with media keys at hand right now)

**Comment by T0biasCZe** [comment]
Well, I realised .NET 4.8.1 doesnt work on W7, so i am gonna downgrade it to .NET 4.8.0 😅

**Comment by T0biasCZe** [comment]
I tested it in Virtual Box and it seems to work
![image](https://github.com/user-attachments/assets/cf55d561-daf1-42af-a228-362c3bbaa2f1)
