### ISSUE TITLE
Discord Rich Presence on v2.1.1 does not work

### ISSUE THREAD

**Issue by ZachjuKamashi** [T0biasCZe/Windows-Media-Player-Discord-RPC#7]
I just downloaded the new release to give it a try but Discord Rich Presence does not work at all despite it being toggled on. I've already tried restarting Discord and WMP RPC, it did not solve the issue.
![Screenshot (718)](https://github.com/T0biasCZe/Windows-Media-Player-Discord-RPC/assets/98941240/6f469042-0477-4484-935c-f08e9bd2faf7)

**Comment by T0biasCZe** [comment]
fixed in 2.1.1c
